package entities;

public class Aposta {
	    private String equipe;
	    private double valor;
	    
	    
	    

	    public Aposta(String equipe, double valor) {
	        this.equipe = equipe;
	        this.valor = valor;
	    }


		public String getEquipe() {
			return equipe;
		}


		public void setEquipe(String equipe) {
			this.equipe = equipe;
		}


		public double getValor() {
			return valor;
		}



	

		

	   
	    
	}


